# Generated by Django 5.1.6 on 2025-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=4)),
                ('value', models.FloatField()),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
    ]
