# Generated by Django 5.1.6 on 2025-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0003_usercurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currencies',
            field=models.ManyToManyField(through='assets.UserCurrency', to='assets.currency'),
        ),
    ]
